cc_binary(
    name = "stadiumseating",
    srcs = ["proj1-stadiumseating/src/main.cpp"],
)

cc_binary(
    name = "boxoffice",
    srcs = ["proj2-boxoffice/src/main.cpp"],
)

cc_binary(
    name = "celsiustofahrenheit",
    srcs = ["proj3-celsiustofahrenheit/src/main.cpp"],
)
